version: '3.9'
services:
  privatenote:
    build: .
    image: erfanghasemi/ccnote:1.4
    volumes:
      - ./.env.docker:/env/.env
    ports:
      - 5000:8080

  redis_DB:
    image: redis:6.2.6-alpine
    command: redis-server --requirepass 123456789
    volumes:
      - redis-volume:/data

volumes:
  redis-volume: