apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: privatenote
  name: privatenote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: privatenote
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: privatenote
    spec:
      containers:
      - image: erfanghasemi/ccnote:1.4
        name: privatenote
        resources: 
          requests:
            cpu: "40m"
        ports:
          - containerPort: 8080
        env:
          - name: REDIS_SECRET
            valueFrom:
              secretKeyRef:
                key: REDIS_PASSWORD
                name: redis-secret

        volumeMounts:
          - mountPath: /env/.env
            subPath: .env
            name: config-map
            readOnly: true
      volumes:
        - name: config-map
          configMap:
            name: privatenote-config
status: {}